"""Added User

Revision ID: 85369dfa93bd
Revises: 3c72ad2d0dfd
Create Date: 2023-04-11 19:07:06.040928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85369dfa93bd'
down_revision = '3c72ad2d0dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_types'), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
